### ISSUE TITLE
Please create a tag for Rocq 9.0 in Rocq Platform 2025.09

### ISSUE THREAD

**Issue by Justme0606** [HoTT/Coq-HoTT#2310]
**Note:There was a compilation error when i tried version 8.20 and Rocq 9.0**

The Rocq team released Rocq `9.0.0` on March 12th, 2025.
The corresponding Rocq Platform release `2025.09` should be released before **Oct 24th, 2025**.
It can be delayed in case of difficulties until Nov 21st, 2025, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (8.20) **does not work** with Rocq `9.0.0`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Rocq Platform CI (unlike Rocq CI) we test only released / tagged versions. Rocq CI is currently testing commit bb95699e33b1a496d7d31e418c0cb837b2acbaa3 on repository https://github.com/HoTT/HoTT - which likely means that this commit does work in Rocq CI.

Could you please create a tag and opam package, or communicate us any existing tag that works with Rocq branch v9.0, **preferably before Sep 26th, 2025**?
In case we might have to delay the Rocq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before Aug 28th, 2025, it will be included in an early Rocq Platform beta release of the for Rocq 9.0.0.

The working branch of Rocq Platform, can be found here [main](https://github.com/rocq-prover/platform/tree/main).
It contains package pick [`~9.0+preview~2025.08`](https://github.com/rocq-prover/platform/tree/main/package_picks/package-pick-9.0+preview~2025.08.sh) which already supports Rocq version `9.0.0` and contains already working (possibly patched / commit pinned) Rocq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Rocq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Rocq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/rocq-prover/platform/issues/481

**Comment by jdchristensen** [comment]
@Alizter Do you know if current HEAD builds with 9.0.0?  If so, can you tag it to handle this issue?

**Comment by Alizter** [comment]
We've already tagged 9.0 a few months ago: https://github.com/HoTT/Coq-HoTT/releases/tag/V9.0

**Comment by jdchristensen** [comment]
@Justme0606 If you switch to our V9.0 tag it should work.  Do we need to do anything else?

**Comment by Justme0606** [comment]
> [@Justme0606](https://github.com/Justme0606) If you switch to our V9.0 tag it should work. Do we need to do anything else?

Hello, perfect!
I just need an opam package coq-hott.9.0, the same as coq-hott.8.20. Would it be possible to create that?

**Comment by Justme0606** [comment]
> [rocq-prover/opam#3522](https://github.com/rocq-prover/opam/pull/3522)

Perfect ! Thanks.
